[server]
headless = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#E8624A"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1A1A1C"
textColor = "#F2EFEA"
font = "sans serif"
